#!/usr/bin/env node
/**
 * Ongoing data pull for BSX Trainer (v0 path — runs on your laptop, secret stays local).
 *
 * Requires your OWN Strava API application (https://www.strava.com/settings/api).
 * Set these env vars (never commit them):
 *   STRAVA_CLIENT_ID, STRAVA_CLIENT_SECRET, STRAVA_REFRESH_TOKEN
 *
 * Writes public/activities.json in the same shape as the seed. It mirrors ADR 0005:
 * load = Strava's relative_effort (suffer_score). Activities without it are skipped.
 *
 * Upgrade path (ADR 0002 / 0005): to self-compute Edwards zone-TRIMP instead, fetch
 * the per-activity HR stream (/activities/:id/streams?keys=heartrate,time) and bin
 * seconds into config.athlete.hrZones — heavier (1 call/activity), but transparent.
 */
import { writeFile } from "node:fs/promises";

const { STRAVA_CLIENT_ID, STRAVA_CLIENT_SECRET, STRAVA_REFRESH_TOKEN } = process.env;
if (!STRAVA_CLIENT_ID || !STRAVA_CLIENT_SECRET || !STRAVA_REFRESH_TOKEN) {
  console.error("Missing STRAVA_CLIENT_ID / STRAVA_CLIENT_SECRET / STRAVA_REFRESH_TOKEN.");
  process.exit(1);
}

const DAYS = 180;

async function accessToken() {
  const res = await fetch("https://www.strava.com/oauth/token", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      client_id: STRAVA_CLIENT_ID,
      client_secret: STRAVA_CLIENT_SECRET,
      grant_type: "refresh_token",
      refresh_token: STRAVA_REFRESH_TOKEN,
    }),
  });
  if (!res.ok) throw new Error(`token: ${res.status} ${await res.text()}`);
  return (await res.json()).access_token;
}

async function fetchActivities(token) {
  const after = Math.floor((Date.now() - DAYS * 864e5) / 1000);
  const out = [];
  for (let page = 1; ; page++) {
    const url = `https://www.strava.com/api/v3/athlete/activities?after=${after}&per_page=100&page=${page}`;
    const res = await fetch(url, { headers: { Authorization: `Bearer ${token}` } });
    if (!res.ok) throw new Error(`activities: ${res.status} ${await res.text()}`);
    const batch = await res.json();
    if (batch.length === 0) break;
    out.push(...batch);
  }
  return out;
}

const token = await accessToken();
const raw = await fetchActivities(token);

const activities = raw
  .filter((a) => typeof a.suffer_score === "number") // relative_effort
  .map((a) => ({
    date: a.start_date_local.slice(0, 10),
    sport: a.sport_type ?? a.type,
    name: a.name,
    movingTimeSec: a.moving_time,
    load: a.suffer_score,
  }))
  .sort((a, b) => a.date.localeCompare(b.date));

const file = {
  generatedAt: new Date().toISOString().slice(0, 10),
  source: "strava:relative_effort",
  note: "Generated by scripts/pull-strava.mjs. Only activities with a Relative Effort are included.",
  activities,
};

await writeFile(new URL("../public/activities.json", import.meta.url), JSON.stringify(file, null, 2) + "\n");
console.log(`Wrote ${activities.length} activities to public/activities.json`);
